public_weserv_headers = files(
    'api_manager.h',
    'config.h',
    'enums.h',
    'env_interface.h',
    'io/source_interface.h',
    'io/target_interface.h',
    'utils/status.h',
)

install_headers(public_weserv_headers, preserve_path: true, subdir: 'weserv')

weserv_includedir = include_directories('..')
